"""Add role and relationship to user

Revision ID: 53425d392230
Revises: a5061da30ce7
Create Date: 2025-09-23 19:03:55.605752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53425d392230'
down_revision = 'a5061da30ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
